name: Build an angular project 
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: docker login
        env: 
          DOC_U: ${{secrets.DOC_U}}
          DOC_P: ${{secrets.DOC_P}}
        run: |
          docker login -u $DOC_U $DOC_P        
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag pjlamb12/angular-cli:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push pjlamb12/angular-cli:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag pjlamb12/angular-cli:latest
      - name: Push the latest Docker image
        run: docker push pjlamb12/angular-cli:latest