name: Build an angular project 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
           

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: docker login
        run: |
          echo ${{ secrets.DOC_P }} | docker login -u ${{ secrets.DOC_U }} --password-stdin   
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag colorlessknight/testrepo:v1  
      - name: Login
        run: echo ${{ secrets.DOC_P }} | docker login -u ${{ secrets.DOC_U }} --password-stdin
      - name: Push the tagged Docker image  
        run: docker push colorlessknight/testrepo:v1
   
   
